"""
Validate the VCF-to-SFS parser against a ground-truth spectrum from msprime/tskit.

A tree sequence simulated under a two-epoch demography has an exact unfolded SFS (from tskit's
``allele_frequency_spectrum``); its genotypes are written to a VCF in which tskit encodes the
ancestral allele as REF, so the parser recovers the correct polarisation with
``skip_non_polarized=False``. The parsed spectrum must reproduce the tskit SFS bin for bin.

The fixtures (VCF + expected SFS) are committed and generated by
``testing/generate_msprime_fixtures.py``; this test needs only sfsutils + numpy, so it runs in CI
without msprime/tskit.
"""
import json
import os
from unittest.mock import patch

import numpy as np
import pytest

import sfsutils as su
from sfsutils.settings import Settings

VCF = "resources/msprime/two_epoch.vcf"
SFS = "resources/msprime/two_epoch.sfs.txt"
REF = "resources/msprime/two_epoch.ref.fasta.gz"

# joint (two-population) fixtures
JOINT_VCF = "resources/msprime/two_epoch_joint.vcf"
JOINT_SFS = "resources/msprime/two_epoch_joint.jsfs.json"
JOINT_POPS = "resources/msprime/two_epoch_joint.pops.json"

# joint (three-population) fixtures
THREE_POP_VCF = "resources/msprime/three_pop_joint.vcf"
THREE_POP_SFS = "resources/msprime/three_pop_joint.jsfs.json"
THREE_POP_POPS = "resources/msprime/three_pop_joint.pops.json"

# two-SFS (two-site) fixtures
TWO_SFS_VCF = "resources/msprime/two_sfs.vcf"
TWO_SFS_REF = "resources/msprime/two_sfs.ref.json"
TWO_SFS_META = "resources/msprime/two_sfs.meta.json"

pytestmark = pytest.mark.skipif(
    not all(os.path.exists(p) for p in (VCF, SFS, REF)),
    reason="msprime fixtures absent",
)

requires_joint = pytest.mark.skipif(
    not all(os.path.exists(p) for p in (JOINT_VCF, JOINT_SFS, JOINT_POPS)),
    reason="joint msprime fixtures absent",
)

requires_three_pop = pytest.mark.skipif(
    not all(os.path.exists(p) for p in (THREE_POP_VCF, THREE_POP_SFS, THREE_POP_POPS)),
    reason="three-population joint msprime fixtures absent",
)

requires_two_sfs = pytest.mark.skipif(
    not all(os.path.exists(p) for p in (TWO_SFS_VCF, TWO_SFS_REF, TWO_SFS_META)),
    reason="two-SFS msprime fixtures absent",
)


def _load_two_sfs_meta():
    """Load the sample size and distance window for the two-SFS fixture."""
    with open(TWO_SFS_META) as f:
        return json.load(f)


def _load_joint_pops():
    """Load the population -> samples mapping and per-population sample sizes for the joint fixture."""
    with open(JOINT_POPS) as f:
        cfg = json.load(f)

    return cfg["pops"], cfg["n"]


def _load_three_pop():
    """Load the population -> samples mapping and per-population sample sizes for the three-pop fixture."""
    with open(THREE_POP_POPS) as f:
        cfg = json.load(f)

    return cfg["pops"], cfg["n"]


def _parsed_and_expected():
    Settings.disable_pbar = True
    expected = np.loadtxt(SFS, dtype=int)
    n = len(expected) - 1
    # skip_non_polarized=False -> use REF (the tskit ancestral allele) as ancestral;
    # subsample_mode='random' takes all haplotypes exactly at full sample size.
    spectra = su.Parser(n=n, source=VCF, skip_non_polarized=False, subsample_mode="random").parse()
    parsed = np.array(spectra["all"].to_list()).astype(int)
    return parsed, expected, n


def test_parser_reproduces_msprime_sfs():
    parsed, expected, n = _parsed_and_expected()
    # polymorphic bins must match the tskit ground truth exactly
    np.testing.assert_array_equal(parsed[1:n], expected[1:n])


def test_parser_recovers_all_segregating_sites():
    parsed, expected, n = _parsed_and_expected()
    assert parsed[1:n].sum() == expected[1:n].sum() > 0


def test_subsample_modes_agree():
    """Probabilistic and random subsampling produce close spectra (replaces the betula test)."""
    Settings.disable_pbar = True
    nn = 10
    prob = su.Parser(source=VCF, n=nn, stratifications=[], subsample_mode="probabilistic",
                     skip_non_polarized=False).parse().all
    rand = su.Parser(source=VCF, n=nn, stratifications=[], subsample_mode="random", seed=2,
                     skip_non_polarized=False).parse().all
    poly = rand.data[1:nn] > 0
    rel_diff = np.abs(prob.data[1:nn] - rand.data[1:nn])[poly] / rand.data[1:nn][poly]
    assert prob.data[1:nn].sum() > 0 and rand.data[1:nn].sum() > 0
    assert rel_diff.mean() < 0.25


def test_target_site_counter_sets_total_n_sites():
    """The TargetSiteCounter scales the spectrum to the requested number of target sites."""
    Settings.disable_pbar = True
    spectra = su.Parser(
        source=VCF, n=20, stratifications=[], skip_non_polarized=False, subsample_mode="random",
        fasta=REF,
        target_site_counter=su.TargetSiteCounter(n_samples=100_000, n_target_sites=50_000),
    ).parse()
    assert spectra.n_sites.sum() == pytest.approx(50_000)


def test_parser_loads_vcf_from_url_offline():
    """The URL branch is exercised without real network by mocking the download to a local file."""
    Settings.disable_pbar = True
    url = "https://example.org/data/two_epoch.vcf"
    expected = np.loadtxt(SFS, dtype=int)
    n = len(expected) - 1
    with patch("sfsutils.io_handlers.download_if_url",
               side_effect=lambda path, *a, **k: VCF if path == url else path):
        spectra = su.Parser(source=url, n=n, stratifications=[], skip_non_polarized=False,
                            subsample_mode="random").parse()
    np.testing.assert_array_equal(np.array(spectra["all"].to_list()).astype(int)[1:n], expected[1:n])


@requires_joint
def test_parser_reproduces_msprime_joint_sfs():
    """The parsed joint (two-population) SFS reproduces the tskit ground truth bin for bin.

    Using the full per-population sample size with ``random`` subsampling makes the hypergeometric
    down-projection deterministic, so the match is exact (as for the single-population fixture).
    """
    Settings.disable_pbar = True
    pops, n = _load_joint_pops()
    truth = np.asarray(su.JointSFS.from_file(JOINT_SFS)).astype(int)

    spectra = su.Parser(source=JOINT_VCF, pops=pops, n=n, skip_non_polarized=False,
                        subsample_mode="random").parse()

    assert isinstance(spectra, su.JointSpectra)
    parsed = np.asarray(spectra["all"]).astype(int)
    assert parsed.shape == truth.shape
    np.testing.assert_array_equal(parsed, truth)


@requires_joint
def test_joint_marginal_matches_single_population():
    """Marginalizing the joint SFS onto one population reproduces that population's single-population SFS."""
    Settings.disable_pbar = True
    pops, n = _load_joint_pops()

    joint = su.Parser(source=JOINT_VCF, pops=pops, n=n, skip_non_polarized=False,
                      subsample_mode="random").parse()

    # marginalize onto population A (axis 0) by summing over the other population
    marginal_a = np.asarray(joint["all"].marginalize([0])).astype(int)

    # parse population A alone from the same VCF
    sfs_a = su.Parser(source=JOINT_VCF, n=n["A"], include_samples=pops["A"],
                      skip_non_polarized=False, subsample_mode="random").parse()
    one_d_a = np.asarray(sfs_a["all"].to_list()).astype(int)

    np.testing.assert_array_equal(marginal_a, one_d_a)


@requires_joint
def test_joint_composes_with_stratifications_and_filtrations():
    """Stratifications and filtrations compose with joint parsing: summing the stratified joint spectra
    recovers the unstratified one, and every type keeps the joint shape."""
    Settings.disable_pbar = True
    pops, n = _load_joint_pops()

    base = su.Parser(source=JOINT_VCF, pops=pops, n=n, skip_non_polarized=False,
                     subsample_mode="random", filtrations=[su.SNPFiltration()]).parse()

    stratified = su.Parser(source=JOINT_VCF, pops=pops, n=n, skip_non_polarized=False,
                           subsample_mode="random", filtrations=[su.SNPFiltration()],
                           stratifications=[su.RandomStratification(n_bins=3, seed=1)]).parse()

    assert set(stratified.types) == {"bin0", "bin1", "bin2"}
    assert stratified.shape == base["all"].shape
    np.testing.assert_array_equal(
        np.asarray(stratified.all).astype(int), np.asarray(base["all"]).astype(int)
    )


@requires_joint
def test_joint_subsample_modes_agree():
    """Down-projecting below the full sample size, probabilistic and random joint subsampling agree closely."""
    Settings.disable_pbar = True
    pops, _ = _load_joint_pops()
    nn = {"A": 6, "B": 4}

    prob = np.asarray(su.Parser(source=JOINT_VCF, pops=pops, n=nn, skip_non_polarized=False,
                                subsample_mode="probabilistic").parse()["all"])
    rand = np.asarray(su.Parser(source=JOINT_VCF, pops=pops, n=nn, skip_non_polarized=False,
                                subsample_mode="random", seed=3).parse()["all"])

    assert prob.shape == (7, 5)
    # each site contributes unit mass in both modes, so the totals are identical
    assert prob.sum() == pytest.approx(rand.sum())

    # the interior distributions are close
    mask = rand > 5
    rel_diff = np.abs(prob[mask] - rand[mask]) / rand[mask]
    assert rel_diff.mean() < 0.3


@requires_three_pop
def test_parser_reproduces_msprime_joint_sfs_three_pops():
    """The parsed three-population joint SFS reproduces the tskit ground truth exactly.

    As for two populations, the full per-population sample size with ``random`` subsampling makes the
    per-population hypergeometric down-projection deterministic, so the outer-product accumulation
    matches tskit's three-way ``allele_frequency_spectrum`` bin for bin.
    """
    Settings.disable_pbar = True
    pops, n = _load_three_pop()
    truth = np.asarray(su.JointSFS.from_file(THREE_POP_SFS)).astype(int)

    spectra = su.Parser(source=THREE_POP_VCF, pops=pops, n=n, skip_non_polarized=False,
                        subsample_mode="random").parse()

    assert isinstance(spectra, su.JointSpectra)
    assert spectra.n_pops == 3
    parsed = np.asarray(spectra["all"]).astype(int)
    assert parsed.shape == truth.shape == (n["A"] + 1, n["B"] + 1, n["C"] + 1)
    np.testing.assert_array_equal(parsed, truth)


@requires_three_pop
def test_three_pop_marginals_match_pairwise_and_single():
    """Marginalizing the three-population joint SFS onto a sub-tuple of axes reproduces the joint SFS
    parsed directly for those populations (pairwise) and for a single population."""
    Settings.disable_pbar = True
    pops, n = _load_three_pop()

    joint = su.Parser(source=THREE_POP_VCF, pops=pops, n=n, skip_non_polarized=False,
                      subsample_mode="random").parse()["all"]

    # marginal onto (A, C) must equal the joint SFS parsed for just A and C
    marginal_ac = np.asarray(joint.marginalize([0, 2])).astype(int)
    pops_ac = {k: pops[k] for k in ("A", "C")}
    n_ac = {k: n[k] for k in ("A", "C")}
    direct_ac = np.asarray(
        su.Parser(source=THREE_POP_VCF, pops=pops_ac, n=n_ac, skip_non_polarized=False,
                  subsample_mode="random").parse()["all"]
    ).astype(int)
    np.testing.assert_array_equal(marginal_ac, direct_ac)

    # marginal onto B alone must equal population B's single-population SFS
    marginal_b = np.asarray(joint.marginalize([1])).astype(int)
    single_b = np.asarray(
        su.Parser(source=THREE_POP_VCF, n=n["B"], include_samples=pops["B"],
                  skip_non_polarized=False, subsample_mode="random").parse()["all"].to_list()
    ).astype(int)
    np.testing.assert_array_equal(marginal_b, single_b)


@requires_two_sfs
def test_parser_reproduces_msprime_two_sfs():
    """The parsed two-SFS reproduces an independent naive windowed pair count bin for bin.

    At the full sample size with ``random`` subsampling, each site's down-projection is a unit mass at its
    derived count, so the outer-product accumulation reduces to the exact integer pair count (symmetrized).
    """
    Settings.disable_pbar = True
    meta = _load_two_sfs_meta()
    ref = np.asarray(su.TwoSFS.from_file(TWO_SFS_REF))

    result = su.Parser(source=TWO_SFS_VCF, n=meta["n"], two_sfs=True, d=meta["distance"],
                       two_sfs_offset=meta["offset"], skip_non_polarized=False,
                       subsample_mode="random").parse()

    assert isinstance(result, su.TwoSpectra)
    sfs2 = result["all"]
    assert isinstance(sfs2, su.TwoSFS)
    assert sfs2.data.shape == ref.shape
    # the matrix is symmetric by construction
    np.testing.assert_allclose(sfs2.data, sfs2.data.T)
    np.testing.assert_allclose(np.asarray(sfs2), ref)


@requires_two_sfs
def test_two_sfs_pair_count_is_projection_invariant():
    """Down-projecting to a smaller sample size preserves the total number of pairs (each pair keeps unit mass)."""
    Settings.disable_pbar = True
    meta = _load_two_sfs_meta()
    ref_total = np.asarray(su.TwoSFS.from_file(TWO_SFS_REF)).sum()

    sfs2 = su.Parser(source=TWO_SFS_VCF, n=10, two_sfs=True, d=meta["distance"],
                     skip_non_polarized=False, subsample_mode="probabilistic").parse()["all"]

    assert sfs2.data.shape == (11, 11)
    np.testing.assert_allclose(sfs2.data, sfs2.data.T)
    assert sfs2.n_sites == pytest.approx(ref_total)


@requires_two_sfs
def test_two_sfs_rejects_incompatible_options():
    """The two-SFS is single-population, so populations are rejected at construction. (A TargetSiteCounter IS
    supported for the unstratified two-SFS, extrapolating the monomorphic pairs; see test_tsc_extrapolation.)"""
    with pytest.raises(NotImplementedError):
        su.Parser(source=TWO_SFS_VCF, n=10, two_sfs=True, pops={"A": ["tsk_0"]})
