"""
Validate the VCF-to-SFS parser against a ground-truth spectrum from msprime/tskit.

A tree sequence simulated under a two-epoch demography has an exact unfolded SFS (from tskit's
``allele_frequency_spectrum``); its genotypes are written to a VCF in which tskit encodes the
ancestral allele as REF, so the parser recovers the correct polarisation with
``skip_non_polarized=False``. The parsed spectrum must reproduce the tskit SFS bin for bin.

The fixtures (VCF + expected SFS) are committed and generated by
``testing/generate_msprime_fixtures.py``; this test needs only sfsutils + numpy, so it runs in CI
without msprime/tskit.
"""
import os
from unittest.mock import patch

import numpy as np
import pytest

import sfsutils as sf
from sfsutils.settings import Settings

VCF = "resources/msprime/two_epoch.vcf"
SFS = "resources/msprime/two_epoch.sfs.txt"
REF = "resources/msprime/two_epoch.ref.fasta.gz"

pytestmark = pytest.mark.skipif(
    not all(os.path.exists(p) for p in (VCF, SFS, REF)),
    reason="msprime fixtures absent",
)


def _parsed_and_expected():
    Settings.disable_pbar = True
    expected = np.loadtxt(SFS, dtype=int)
    n = len(expected) - 1
    # skip_non_polarized=False -> use REF (the tskit ancestral allele) as ancestral;
    # subsample_mode='random' takes all haplotypes exactly at full sample size.
    spectra = sf.Parser(n=n, vcf=VCF, skip_non_polarized=False, subsample_mode="random").parse()
    parsed = np.array(spectra["all"].to_list()).astype(int)
    return parsed, expected, n


def test_parser_reproduces_msprime_sfs():
    parsed, expected, n = _parsed_and_expected()
    # polymorphic bins must match the tskit ground truth exactly
    np.testing.assert_array_equal(parsed[1:n], expected[1:n])


def test_parser_recovers_all_segregating_sites():
    parsed, expected, n = _parsed_and_expected()
    assert parsed[1:n].sum() == expected[1:n].sum() > 0


def test_subsample_modes_agree():
    """Probabilistic and random subsampling produce close spectra (replaces the betula test)."""
    Settings.disable_pbar = True
    nn = 10
    prob = sf.Parser(vcf=VCF, n=nn, stratifications=[], subsample_mode="probabilistic",
                     skip_non_polarized=False).parse().all
    rand = sf.Parser(vcf=VCF, n=nn, stratifications=[], subsample_mode="random", seed=2,
                     skip_non_polarized=False).parse().all
    poly = rand.data[1:nn] > 0
    rel_diff = np.abs(prob.data[1:nn] - rand.data[1:nn])[poly] / rand.data[1:nn][poly]
    assert prob.data[1:nn].sum() > 0 and rand.data[1:nn].sum() > 0
    assert rel_diff.mean() < 0.25


def test_target_site_counter_sets_total_n_sites():
    """The TargetSiteCounter scales the spectrum to the requested number of target sites."""
    Settings.disable_pbar = True
    spectra = sf.Parser(
        vcf=VCF, n=20, stratifications=[], skip_non_polarized=False, subsample_mode="random",
        fasta=REF,
        target_site_counter=sf.TargetSiteCounter(n_samples=100_000, n_target_sites=50_000),
    ).parse()
    assert spectra.n_sites.sum() == pytest.approx(50_000)


def test_parser_loads_vcf_from_url_offline():
    """The URL branch is exercised without real network by mocking the download to a local file."""
    Settings.disable_pbar = True
    url = "https://example.org/data/two_epoch.vcf"
    expected = np.loadtxt(SFS, dtype=int)
    n = len(expected) - 1
    with patch("sfsutils.io_handlers.download_if_url",
               side_effect=lambda path, *a, **k: VCF if path == url else path):
        spectra = sf.Parser(vcf=url, n=n, stratifications=[], skip_non_polarized=False,
                            subsample_mode="random").parse()
    np.testing.assert_array_equal(np.array(spectra["all"].to_list()).astype(int)[1:n], expected[1:n])
