"""
Validate the VCF-to-SFS parser against a ground-truth spectrum from msprime/tskit.

A tree sequence simulated under a two-epoch demography has an exact unfolded SFS (from tskit's
``allele_frequency_spectrum``); its genotypes are written to a VCF in which tskit encodes the
ancestral allele as REF, so the parser recovers the correct polarisation with
``skip_non_polarized=False``. The parsed spectrum must reproduce the tskit SFS bin for bin.

The fixtures (VCF + expected SFS) are committed and generated by
``testing/generate_msprime_fixtures.py``; this test needs only sfsutils + numpy, so it runs in CI
without msprime/tskit.
"""
import os

import numpy as np
import pytest

import sfsutils as sf
from sfsutils.settings import Settings

VCF = "resources/msprime/two_epoch.vcf"
SFS = "resources/msprime/two_epoch.sfs.txt"

pytestmark = pytest.mark.skipif(
    not (os.path.exists(VCF) and os.path.exists(SFS)),
    reason="msprime fixtures absent",
)


def _parsed_and_expected():
    Settings.disable_pbar = True
    expected = np.loadtxt(SFS, dtype=int)
    n = len(expected) - 1
    # skip_non_polarized=False -> use REF (the tskit ancestral allele) as ancestral;
    # subsample_mode='random' takes all haplotypes exactly at full sample size.
    spectra = sf.Parser(n=n, vcf=VCF, skip_non_polarized=False, subsample_mode="random").parse()
    parsed = np.array(spectra["all"].to_list()).astype(int)
    return parsed, expected, n


def test_parser_reproduces_msprime_sfs():
    parsed, expected, n = _parsed_and_expected()
    # polymorphic bins must match the tskit ground truth exactly
    np.testing.assert_array_equal(parsed[1:n], expected[1:n])


def test_parser_recovers_all_segregating_sites():
    parsed, expected, n = _parsed_and_expected()
    assert parsed[1:n].sum() == expected[1:n].sum() > 0
